/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Services.Services.IPL.khachhangIPL;
import Service.Services.khachHangServices;
import Viewmodel.KhachHangviewmodel;
import Viewmodel.ThemNhanhKHViewModel;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author HP
 */
public class BangthemMoiKHNhanh extends javax.swing.JFrame {
     khachhangIPL khaHangServices = new khachHangServices();
    private final String SDT_REGEX = "(0)+([0-9]{9})";
    DefaultTableModel dtm;
    /**
     * Creates new form BangthemMoiKHNhanh
     */
    public BangthemMoiKHNhanh() {
        initComponents();
        setLocationRelativeTo(null);
         loadata();
//         JOptionPane.showMessageDialog(this, themNhanhKH_BanHang.tenkh);
    
    }

  public void loadata() {
        dtm = (DefaultTableModel) tb_themNhanhKH.getModel();
        dtm.setRowCount(0);
        List<KhachHangviewmodel> kh = khaHangServices.getallDB();
        for (KhachHangviewmodel x : kh) {
            dtm.addRow(new Object[]{
                x.getMaKH(),
                x.getHotenKH(),
                x.getSDT(),
                x.getDiachi(),});

        }

    }
// public static void AddRowToJTable(Object[] dataRow)
//    {
//        DefaultTableModel dtm = (DefaultTableModel) tb_themNhanhKH.getModel();
//        model.addRow(dataRow);
//    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_themNhanhKH = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_themNhanhKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "SÐT", "Địa Chỉ"
            }
        ));
        tb_themNhanhKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_themNhanhKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_themNhanhKH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_themNhanhKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_themNhanhKHMouseClicked
    BanHang banHang = new BanHang();
        int row = tb_themNhanhKH.getSelectedRow();
        TableModel model = tb_themNhanhKH.getModel();
    String ten = model.getValueAt(row, 0).toString();
      String sdt = model.getValueAt(row, 1).toString();
        String diachi = model.getValueAt(row, 2).toString();
        banHang.setVisible(true);
        banHang.pack();
        dispose();
        banHang.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        banHang.txt_khachhang.setText(ten);
         banHang.txt_sdtkh.setText(sdt);
          banHang.txt_diachiKH.setText(diachi);
    }//GEN-LAST:event_tb_themNhanhKHMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BangthemMoiKHNhanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BangthemMoiKHNhanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BangthemMoiKHNhanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BangthemMoiKHNhanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BangthemMoiKHNhanh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_themNhanhKH;
    // End of variables declaration//GEN-END:variables
}
