/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Model.Khachhang;
import Services.Services.IPL.khachhangIPL;
import Service.Services.khachHangServices;
import Viewmodel.KhachHangviewmodel;
import java.awt.JobAttributes;
import java.io.ObjectOutput;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class KhachHang extends javax.swing.JFrame {
   Connection con;
    PreparedStatement pst;
    khachhangIPL khaHangServices = new khachHangServices();
    private final String SDT_REGEX = "(0)+([0-9]{9})";
    DefaultTableModel dtm;

    /**
     * Creates new form Login
     */
    public KhachHang() {
        initComponents();
        setLocationRelativeTo(null);
        loadata();
        
    }
      private void makhachhang() throws SQLException{
                   try {
                        Statement s = con.createStatement();
                     ResultSet rs = s.executeQuery("select MaKH from KhachHang");
                      rs.next();
                       rs.getString("MaKH");
                        if (rs.getString("MaKH") == null) {
                txt_makh.setText("KH01");    
            } else {
                long id = Long.parseLong(rs.getString("MaKH)").substring(2, rs.getString("MaKH").length()));
                id++;
                txt_makh.setText("KH" + String.format("%07d", id));
            }
                  } catch (Exception e) {
                  }
              }
    public void loadata() {
        dtm = (DefaultTableModel) TB_khachhang.getModel();
        dtm.setRowCount(0);
        List<KhachHangviewmodel> kh = khaHangServices.getallDB();
        for (KhachHangviewmodel x : kh) {
            dtm.addRow(new Object[]{
                dtm.getRowCount() + 1,
                x.getMaKH(),
                x.getHotenKH(),
                x.getSDT(),
                x.getDiachi(),});

        }

    }

    public Khachhang getdata() {
        Khachhang kh = new Khachhang();
        kh.setMaKH(txt_makh.getText());
        kh.setHotenKH(txt_hoten.getText());
        kh.setSDT(txt_sdt.getText());
        kh.setDiachi(txt_diachi.getText());
        return kh;
    }

    public boolean validatekhachhang() {
        if (txt_makh.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong ma");
            txt_makh.requestFocus();
            return false;
        }
        if (txt_hoten.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong ten");
            txt_hoten.requestFocus();
            return false;
        }

        if (txt_diachi.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong dia chi");
            txt_diachi.requestFocus();
            return false;
        }
        if (txt_sdt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong SDT");
            txt_sdt.requestFocus();
            return false;
        } else if (!txt_sdt.getText().trim().matches(SDT_REGEX)) {
            JOptionPane.showMessageDialog(this, "Số Điện Thoại phải gồm 10 số");
            txt_sdt.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPopuMenu1 = new rojerusan.RSPopuMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_khachhang = new rojeru_san.complementos.RSTableMetro();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_diachi = new app.bolivia.swing.JCTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_xoa = new rojerusan.RSMaterialButtonCircle();
        btn_sua = new rojerusan.RSMaterialButtonCircle();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_hoten = new app.bolivia.swing.JCTextField();
        txt_sdt = new app.bolivia.swing.JCTextField();
        txt_makh = new app.bolivia.swing.JCTextField();
        btn_them1 = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Nhập");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TB_khachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã KH", "Ho va tên", "SÐT", "Ðia Chi"
            }
        ));
        TB_khachhang.setColorBackgoundHead(new java.awt.Color(102, 102, 255));
        TB_khachhang.setColorBordeFilas(new java.awt.Color(102, 102, 255));
        TB_khachhang.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        TB_khachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TB_khachhangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TB_khachhang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 620, 130));

        jLabel15.setBackground(new java.awt.Color(255, 51, 51));
        jLabel15.setFont(new java.awt.Font("Sitka Display", 0, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("Quản lý Khách Hàng");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 630, 610));

        jPanel2.setBackground(new java.awt.Color(102, 102, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Sitka Display", 0, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mã Khách Hàng");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txt_diachi.setBackground(new java.awt.Color(102, 102, 255));
        txt_diachi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_diachi.setPlaceholder("Enter Ðia Chi ...");
        txt_diachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diachiActionPerformed(evt);
            }
        });
        jPanel2.add(txt_diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel12.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Họ và Tên");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SÐT");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel14.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Địa Chỉ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        btn_xoa.setBackground(new java.awt.Color(255, 51, 51));
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 140, 30));

        btn_sua.setBackground(new java.awt.Color(255, 51, 51));
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 140, 30));

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));

        jLabel3.setBackground(new java.awt.Color(255, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image da1/icons8_Rewind_48px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        txt_hoten.setBackground(new java.awt.Color(102, 102, 255));
        txt_hoten.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_hoten.setPlaceholder("Enter Ho va ten ...");
        txt_hoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hotenActionPerformed(evt);
            }
        });
        jPanel2.add(txt_hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        txt_sdt.setBackground(new java.awt.Color(102, 102, 255));
        txt_sdt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_sdt.setPlaceholder("Enter SÐT ...");
        txt_sdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sdtActionPerformed(evt);
            }
        });
        jPanel2.add(txt_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        txt_makh.setBackground(new java.awt.Color(102, 102, 255));
        txt_makh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_makh.setPlaceholder("Enter Mã Khách Hàng ...");
        txt_makh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_makhActionPerformed(evt);
            }
        });
        jPanel2.add(txt_makh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        btn_them1.setBackground(new java.awt.Color(255, 51, 51));
        btn_them1.setText("Thêm");
        btn_them1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_them1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_them1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 140, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 830));

        setSize(new java.awt.Dimension(1090, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_diachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diachiActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Trangchu trangchu = new Trangchu();
        trangchu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txt_hotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hotenActionPerformed

    private void txt_sdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sdtActionPerformed

    private void txt_makhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_makhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_makhActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed

        int row = TB_khachhang.getSelectedRow();
        String id = txt_makh.getText();
        int hoi = JOptionPane.showConfirmDialog(this, "Ban co muon xoa khong? ", "Xoa", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (hoi == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Ban da xoa thanh cong");
            khaHangServices.Delete(id);
            loadata();
        }

    }//GEN-LAST:event_btn_xoaActionPerformed

    private void TB_khachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TB_khachhangMouseClicked
        int row = TB_khachhang.getSelectedRow();
        txt_makh.setText(TB_khachhang.getValueAt(row, 1) + "");
        txt_hoten.setText(TB_khachhang.getValueAt(row, 2) + "");
        txt_sdt.setText(TB_khachhang.getValueAt(row, 3) + "");
        txt_diachi.setText(TB_khachhang.getValueAt(row, 4) + "");

    }//GEN-LAST:event_TB_khachhangMouseClicked

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        Khachhang kh = new Khachhang();
        kh.setMaKH(txt_makh.getText());
        kh.setHotenKH(txt_hoten.getText());
        kh.setSDT(txt_sdt.getText());
        kh.setDiachi(txt_diachi.getText());
        try {
            khaHangServices.Update(kh);
            loadata();
            JOptionPane.showMessageDialog(this, "Sua thanh cong");

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_them1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_them1ActionPerformed
        try {
            Khachhang kh = getdata();
            if (validatekhachhang()) {
                int ok = JOptionPane.showConfirmDialog(this, "Ban co muon them", "Them", JOptionPane.YES_OPTION);
                if (ok == JOptionPane.YES_OPTION) {

                    khaHangServices.add(kh);
                    loadata();
                    JOptionPane.showMessageDialog(this, "Them thanh cong");

                }
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_them1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSTableMetro TB_khachhang;
    private rojerusan.RSMaterialButtonCircle btn_sua;
    private rojerusan.RSMaterialButtonCircle btn_them1;
    private rojerusan.RSMaterialButtonCircle btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSPopuMenu rSPopuMenu1;
    private app.bolivia.swing.JCTextField txt_diachi;
    private app.bolivia.swing.JCTextField txt_hoten;
    private app.bolivia.swing.JCTextField txt_makh;
    private app.bolivia.swing.JCTextField txt_sdt;
    // End of variables declaration//GEN-END:variables
}
