/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Model.Khachhang;
import Services.Services.IPL.khachhangIPL;
import Service.Services.khachHangServices;
import Viewmodel.KhachHangviewmodel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class themNhanhKH_BanHang extends javax.swing.JFrame {

    khachhangIPL khaHangServices = new khachHangServices();
    private final String SDT_REGEX = "(0)+([0-9]{9})";
    DefaultTableModel dtm;
   

    /**
     * Creates new form themnhanhNhanVien_BanHang
     */
    public themNhanhKH_BanHang() {
        initComponents();
        setLocationRelativeTo(null);

    }

     public Khachhang getdata() {
        Khachhang kh = new Khachhang();
        kh.setMaKH(txt_makh.getText());
        kh.setHotenKH(txt_tenkh.getText());
        kh.setSDT(txt_sdt.getText());
        kh.setDiachi(txt_diachi.getText());
        return kh;
    }


    public boolean validatekhachhang() {
        if (txt_makh.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong ma");
            txt_makh.requestFocus();
            return false;
        }
        if (txt_tenkh.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong ten");
            txt_tenkh.requestFocus();
            return false;
        }

        if (txt_diachi.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong dia chi");
            txt_diachi.requestFocus();
            return false;
        }
        if (txt_sdt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong SDT");
            txt_sdt.requestFocus();
            return false;
        } else if (!txt_sdt.getText().trim().matches(SDT_REGEX)) {
            JOptionPane.showMessageDialog(this, "Số Điện Thoại Không Đúng Định Dạng");
            txt_sdt.requestFocus();
            return false;
        }
        return true;
    }

//    public static void AddRowToJTable(Object[] dataRow) {
//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//        model.addRow(dataRow);
//    }
//    public static String tenkh ="4354";

    
//    public void addnhanh() {
//        try {
////          BangthemMoiKHNhanh.ad 
//            KhachHangviewmodel kh = getdata();
//            if (validatekhachhang()) {
//                int ok = JOptionPane.showConfirmDialog(this, "Ban co muon them", "Them", JOptionPane.YES_OPTION);
//                if (ok == JOptionPane.YES_OPTION) {
//                    khaHangServices.tauNhanh();
//                    tenkh = txt_tenkh.getText();
//                    JOptionPane.showMessageDialog(this, "Them thanh cong");
//                    BangthemMoiKHNhanh theBangthemMoiKHNhanh = new BangthemMoiKHNhanh();
//                    theBangthemMoiKHNhanh.setVisible(true);
//                    dispose();
//
//                }
//            }
//
//        } catch (Exception e) {
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_makh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_tenkh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_diachi = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Khách Hàng");

        jLabel2.setText("Mã KH");

        jLabel3.setText("Tên Khách Hàng");

        jLabel4.setText("SÐT");

        jLabel5.setText("Dia Chi");

        btn_add.setText("Thêm");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_makh)
                            .addComponent(txt_tenkh)
                            .addComponent(txt_sdt)
                            .addComponent(txt_diachi, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_add)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_makh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btn_add)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
   try {
            Khachhang kh = getdata();
            if (validatekhachhang()) {
                int ok = JOptionPane.showConfirmDialog(this, "Ban co muon them", "Them", JOptionPane.YES_OPTION);
                if (ok == JOptionPane.YES_OPTION) {

                    khaHangServices.add(kh);
//                    loadata();
                    JOptionPane.showMessageDialog(this, "Them thanh cong");
                    BangthemMoiKHNhanh theBangthemMoiKHNhanh = new BangthemMoiKHNhanh();
                    theBangthemMoiKHNhanh.setVisible(true);
                    dispose();
                }
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(themNhanhKH_BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(themNhanhKH_BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(themNhanhKH_BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(themNhanhKH_BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new themNhanhKH_BanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_makh;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tenkh;
    // End of variables declaration//GEN-END:variables
}
